name: Run Jest Tests

on: [push, pull_request]

jobs:
  jest-tests:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test
